language: php
dist: trusty
matrix:
  include:
    - php: 5.3
      dist: precise
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
install: composer install
script: phpunit --configuration phpunit.xml
